### ISSUE TITLE
Customers namespace | view invoice

### ISSUE THREAD

**Issue by rapidos** [moduloTech/open_invoice_first_try#3]
The url should be in format /ext/invoices/:uuid

the app should respond_to do |format|
- format.html
- format.json

# HTML format
the 50% left portion should display the PDF of the invoice
the 50% of the right portion should display all the available informations about the invoice

# Json format
should display all the available information about the invoice + a direct link to the invoice PDF.

**Comment by balbesina** [comment]
ready
