### ISSUE TITLE
Customers namespace | download pdf image

### ISSUE THREAD

**Issue by rapidos** [moduloTech/open_invoice_first_try#4]
Whenever a PDF for an invoice is requested it should go through a dedicated action located at: /ext/invoices/:uuid.pdf that will store each and every access to the invoice

At the moment I see the following triggers:
- When sending the invoice to the customer, the PDF should be downloadable from this link
- When opening it from the /ext/invoices/:uuid page
- When downloading from the /ext/invoices/:uuid.json feed

**Comment by balbesina** [comment]
ready
